{"uuid": "39e890fd-ae3c-4568-b4c0-ad57af297edd", "children": ["7446f49d-2fa5-4777-a03a-9f829431959c"], "befores": [{"name": "setupbrowser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=132.0.6834.197)\nStacktrace:\n\tGetHandleVerifier [0x00007FF6835A02F5+28725]\n\t(No symbol) [0x00007FF683502AE0]\n\t(No symbol) [0x00007FF68339510A]\n\t(No symbol) [0x00007FF68336EEA5]\n\t(No symbol) [0x00007FF683416F87]\n\t(No symbol) [0x00007FF68342FA52]\n\t(No symbol) [0x00007FF68340FD53]\n\t(No symbol) [0x00007FF6833DA0E3]\n\t(No symbol) [0x00007FF6833DB471]\n\tGetHandleVerifier [0x00007FF6838CF30D+3366989]\n\tGetHandleVerifier [0x00007FF6838E12F0+3440688]\n\tGetHandleVerifier [0x00007FF6838D78FD+3401277]\n\tGetHandleVerifier [0x00007FF68366AAAB+858091]\n\t(No symbol) [0x00007FF68350E74F]\n\t(No symbol) [0x00007FF68350A304]\n\t(No symbol) [0x00007FF68350A49D]\n\t(No symbol) [0x00007FF6834F8B69]\n\tBaseThreadInitThunk [0x00007FF8292F7374+20]\n\tRtlUserThreadStart [0x00007FF82A31CC91+33]\n\n", "trace": "  File \"C:\\Users\\Dell\\PycharmProjectHRMS.PYTEST\\pythonProject\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Dell\\PycharmProjectHRMS.PYTEST\\pythonProject\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\Dell\\PycharmProjectHRMS.PYTEST\\pythonProject\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Dell\\PycharmProjectHRMS.PYTEST\\pythonProject\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Dell\\PycharmProjectHRMS.PYTEST\\pythonProject\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\Dell\\PycharmProjectHRMS.PYTEST\\pythonProject\\tests\\conftest.py\", line 54, in setupbrowser\n    driver.maximize_window()\n    ~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\Dell\\PycharmProjectHRMS.PYTEST\\pythonProject\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 536, in maximize_window\n    self.execute(command, None)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Dell\\PycharmProjectHRMS.PYTEST\\pythonProject\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 384, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"C:\\Users\\Dell\\PycharmProjectHRMS.PYTEST\\pythonProject\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1739780146391, "stop": 1739780150735}], "start": 1739780146391, "stop": 1739780151438}